#!/bin/bash
curl -X POST --data-urlencode 'payload={"channel": "#richandroyal", "username": "deployer", "text": "TI deploy"}' https://symmetrics.slack.com/services/hooks/incoming-webhook?token=mBf7uPf4mJNgZ86K6d4xwXqD
fab ti deploy
